[[intro]]
== ElasticSearch最新版本7.4.2怎么用？小白边学边总结

1.	环境配置
用ElasticSearch来查找数据，首先要安装ElasticSearch软件。去ElasticSearch官网下载自己电脑系统对应的软件包就可以。
安装ElasticSearch软件后，还需要再下载一个配套的软件，这个软件是一个可视化窗口，在这里输入命令行（就是写类似代码的东西）。跟ElasticSearch配套使用的可视化窗口软件有很多，我这里用的是Kibana软件（还有个叫Curl的软件）。这个Kibana软件在ElasticSearch官网中找到后下载即可。

下载链接：
鉴于很多中国大陆的同学翻墙困难，安装软件需要很长时间。我特此将V7.4.2版本的ElasticSearch 和Kibana软件包（Windows, Linux, Mac三种系统的都有）保存到了我的百度网盘中，

下载链接：https://pan.baidu.com/s/1KW9nenxUmlOir9WqFHM0Eg 

提取码：3iik

当然如果你电脑连有VPN，能实现翻墙自由，那你也可以直接在ElasticSearch官网上下载，

官网链接：https://www.elastic.co/cn/downloads/elasticsearch


跟之前版本的对比：
我对比了ES旧版本的安装方法，V7.0版本之前的ES下载安装后还需要你自己配置Java语言环境，也即是去JDK官网下载安装Java Development Kit。但是V7.0版本之后的就不需要再自己配置Java语音环境了，因为之后的版本ES包中都包含了JDK文件，ES下载安装后可以直接使用。这使ES的使用更简单了，但是一个缺点就是ES压缩包由原来的100MB变成了300MB！


2.	如何开始运行ElasticSearch?

如果你的电脑是Windows系统：找到自己的ElasticSearch文件夹，找到bin目录，运行ElasticSearch.bat文件后出现一个黑色窗口。如果你的电脑是Mac系统或Linux系统，那你就可以直接在bin目录下运行elasticsearch文件。等待窗口自动运行完后，就算是已经启动ElasticSearch了。

之后可以验证一下ElasticSearch是否启动成功：打开浏览器，在里面输入http://localhost:9200
 
3.	打开Kibana
Kibana才是最后我们要写命令行的地方。只有先成功运行ElasticSearch后Kibana才能成功运行。
同样，找到自己的Kibana文件夹，打开bin文件，点击Kibana.bat文件后又出现一个黑色窗口, 等待窗口自动运行完后，就算是已经启动Kibana了。

 

之后打开Kibana操作界面，方法是：打开浏览器，输入：http://localhost:5601 

点击左侧列的开发工具这个扳手图片，我们的命令行页面就出来了！
 


